title: Production
icon: i-fluent-manufacturer-24-regular
description: Pilotez votre production avec précision pour une efficacité maximale.
application: Dokos
navigation:
    title: Production
    icon: i-fluent-manufacturer-24-regular
    description: De l'achat des matières premières à la création de produits finis