navigation:
    title: Production
    icon: i-fluent-manufacturer-24-regular
    description: Planification et suivi de la production manufacturière.

title: Production
icon: i-fluent-manufacturer-24-regular
description: Pilotez votre production avec précision pour une efficacité maximale.
application: Dokos
author: Frappe Technologies & Contributeurs

hero:
  title: Pilotez avec précision votre <span class="text-primary">production</span> pour une efficacité maximale.
  description: Avec Dokos, simplifiez vos opérations de production, économisez du temps précieux et assurez une qualité irréprochable à chaque étape.
  links:
    - label: Commencez maintenant
      to: https://cloud.dokos.io
      size: sm
      color: amber
      variant: solid
      icon: i-heroicons-rocket-launch
    - label: Documentation
      to: https://doc.dokos.io
      size: sm
      color: gray
      icon: i-heroicons-arrow-right-20-solid
      trailing: true
  headline:
    label: L'écosystème Dokos
    color: sky
    to: "/fr"
    right_icon: i-heroicons-arrow-right-20-solid

features:
  - title: Optimisez votre Production
    description: Gagnez en visibilité et en contrôle sur vos processus de production. <br><br>Avec Dokos, définissez rapidement les composants nécessaires et assurez une gestion fluide et sans erreurs. <br><br>La flexibilité du logiciel vous permet également de gérer facilement les différentes variantes de produits, en adaptant rapidement les nomenclatures et les coûts associés à chaque version.</br>
    image: "image/production/Nomenclature.svg"
    image_bg_color: "bg-teal-500"
    align: left
    badge:
      label: Gestion des articles et Nomenclature
      color: sky
  - title: Gagnez en efficacité sur votre plannification
    description: Planifiez vos productions avec confiance. <br><br>Anticipez les besoins et assurez des pratiques de production durables pour plus de sérénité.<br><br> Evitez les surplus et les pénuries, tout en respectant des pratiques de production durables et responsables.</br>
    image: "image/production/plannification_production.png"
    image_bg_color: "bg-teal-500"
    align: right
    badge:
      label: Demande de Production et Plannification
      color: sky
  - title: Restez informé en temps réel 
    description: Le suivi des opérations de production est simplifié grâce à un tableau de bord dynamique qui vous offre une vue d'ensemble de l'avancement de chaque ordre de fabrication.<br><br> Vous pouvez enregistrer les temps consacrés à chaque étape de production, ce qui vous aide à maximiser l’efficacité de vos processus et à identifier facilement les axes d'amélioration.</br>
    video: "/image/production/tableau-de-bord-production.mp4"
    image_bg_color: "bg-teal-500"
    align: left
    badge:
      label: Suivi des Opérations de Production
      color: sky
  - title: Garantissez la qualité à chaque étape
    description: La qualité est au cœur de notre approche. <br><br>Dokos intègre des contrôles qualité à chaque phase de production, vous permettant de garantir des produits conformes. <br><br>Avec des contrôles intégrés et des rapports détaillés, gagnez la confiance de vos clients en livrant des produits conformes à chaque fois.</br>
    image: "image/production/qualite.svg"
    image_bg_color: "bg-teal-500"
    align: right
    badge:
      label: Contrôle Qualité
      color: sky
  - title: Optimisez votre gestion de stocks
    description: Bénéficiez d'un suivi en temps réel des niveaux de matières premières et de produits finis. <br><br>Vous pouvez organiser efficacement vos stocks et optimiser les mouvements entre entrepôts. <br><br>Vous pouvez également évaluer les coûts de production en intégrant les matières premières, la main-d'œuvre et les frais généraux, ce qui facilite une gestion budgétaire éclairée et responsable.</br>
    image: "image/stock/quatre-tableau-de-bord-stock.svg"
    image_bg_color: "bg-teal-500"
    align: left
    badge:
      label: Gestion de Stock
      color: sky
  - title: Prenez des décisions éclairées
    description: Générez avec Dokos des rapports personnalisés vous permettant de prendre des décisions éclairées, basées sur des données précises.<br><br> En analysant les tendances, vous identifiez les opportunités d’amélioration pour rester compétitif sur le marché.</br>
    image: "image/production/tableau-de-bord-production-image-1800.svg"
    image_bg_color: "bg-teal-500"
    align: right
    badge:
      label: Rapports
      color: sky
  - title: Une solution éthique et transparente pour une production optimisée.
    description: En choisissant Dokos, vous rejoignez une communauté engagée qui partage vos valeurs. <br><br>Profitez d’une solution open-source innovante, conçue pour garantir transparence, performance et éthique dans votre gestion de production.</br>
    image: "image/dokos-communaute.png"
    image_bg_color: "bg-teal-500"
    align: left
    badge:
      label: Un choix éthique
      color: sky


plus_button:
  label: Découvrir toutes nos fonctionnalités
  icon: i-heroicons-outline-plus-circle
  size: lg
  color: sky
  to: /features/production

bottom_cta:
  title: Révolutionnez dès aujourd'hui la gestion de votre production avec Dokos.
  class: "bg-amber-600/10 dark:bg-amber-800/10"
  links:
    - label: Commencez maintenant
      to: https://cloud.dokos.io
      size: sm
      color: sky
      variant: solid
      icon: i-heroicons-rocket-launch
    - label: Documentation
      to: https://doc.dokos.io
      size: sm
      variant: ghost
      color: gray
      icon: i-heroicons-arrow-right-20-solid
      trailing: true